In [36]:
%matplotlib inline 
import matplotlib
import pandas as pd
from pandas import read_csv, DataFrame
import numpy
from numpy import linalg
import scipy

In [53]:
import nltk
from nltk.stem.snowball import RussianStemmer
stemmer = RussianStemmer()

In [4]:
import bokeh
from bokeh.models import ColumnDataSource, HoverTool, HBox, VBoxForm
from bokeh.models.widgets import Slider, Select, TextInput
from bokeh.io import curdoc
from bokeh.plotting import figure, output_file, output_notebook, show, ColumnDataSource, gridplot

In [5]:
from pandas.io import parsers
import sys
import os
import codecs
sys.stdout = codecs.getwriter('cp866')(sys.stdout,'replace')

In [7]:
text = []
f = open('answer1.txt',encoding="utf8")
text.append(f.read())
f = open('answer2.txt',encoding="utf8")
text.append(f.read())
f = open('answer3.txt',encoding="utf8")
text.append(f.read())
f = open('answer4.txt',encoding="utf8")
text.append(f.read())

In [19]:
s = pd.read_table('C:/Users/kosti/Desktop/питон/txt_answer/answer1.txt', encoding='utf-8', error_bad_lines=False, nrows=5)
s

Воспитатель не учел желание детей , уже игравших в игру . У детей уже сложилась своя игра и роль Ларисе в этой игре должны были дать сами дети , а не воспитатель. Она должна была спросить желание девочки Ларисы хочет ли она участвовать в игре , а также спросить группу детей , уже игравших , примут ли они Ларису в свою игру . Воспитатель своим действием , нарушила правила игры , придуманные детьми , ей следовало  принять роль , и войти в игру под видом клиента  . 
0  Воспитатель не должен был включать Ларису в уж...                                                                                                                                                                                                                                                                                                                                                                                                                                 
1  Ошибка воспитателя в том, что она не дала возм...                                                                                                                                                                                                                                                                                                                                                                                                                                 
2  Ошибка воспитателя в том,что она включила Лари...                                                                                                                                                                                                                                                                                                                                                                                                                                 
3  Авторитарный подход педагога к организации игр...                                                                                                                                                                                                                                                                                                                                                                                                                                 
4  Сюжетно-ролевая игра заключается в том, что де...

In [24]:
result = s.unstack()
result

Воспитатель не учел желание детей , уже игравших в игру . У детей уже сложилась своя игра и роль Ларисе в этой игре должны были дать сами дети , а не воспитатель. Она должна была спросить желание девочки Ларисы хочет ли она участвовать в игре , а также спросить группу детей , уже игравших , примут ли они Ларису в свою игру . Воспитатель своим действием , нарушила правила игры , придуманные детьми , ей следовало  принять роль , и войти в игру под видом клиента  .   0    Воспитатель не должен был включать Ларису в уж...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1    Ош

In [29]:
table = result.1
table

SyntaxError: invalid syntax (<ipython-input-29-a857b5d0d6da>, line 1)

In [30]:
ignorechars = '''(){},:'!'''
stopwords = ['там','где','как','он','мы','так','в','на','о','об','не','но','по','а','и','все','это','при','с','S','было','быть','был','много','однако','те','нами','теми','то','есть','ему','его','сих','пор','же','во','под','если','ли','у','.','та','со','за','ту','них','к','для','того','чтобы','бы','из','до','или','ни','эт','котор','что','ил']

In [45]:
exec(open('LSI_py3.py', encoding="utf8").read())

In [46]:
lsa = LSI(stopwords, ignorechars, text)

In [47]:
lsa.build()

In [48]:
lsa.calc()

 Сингулярное разложение

In [55]:
lsa.print_svd()

�������� ���祭��
[ 1238.387   532.849   342.153   206.215]
���� 3 ���窨 Vt �����
[[ 0.556  0.429  0.465  0.54 ]
 [-0.804  0.127  0.499  0.297]
 [-0.208  0.514 -0.717  0.423]]


Координаты слов на плоскости (2-я и 3-я компоненты)

In [59]:
df = pd.DataFrame(-1*lsa.U[:,1:3])
df = df.rename(columns={0:'x', 1:'y'})
df.insert(2,'dots', [lsa.fulldictionary[i] for i in lsa.keys])
df[:10]

x         y         dots
0 -0.298407 -0.203456  воспитатель
1 -0.037725 -0.015197         учел
2 -0.028797 -0.018298      желание
3  0.333455  0.133329        детей
4  0.022270 -0.003493             
5 -0.045335 -0.041798          уже
6 -0.070868 -0.051125     игравших
7 -0.088106  0.243524         игру
8 -0.009054 -0.003647    сложилась
9 -0.045660  0.036610         своя

Координаты частей ответов на плоскости

In [60]:
doc_coord = pd.DataFrame(-1*lsa.Vt[1:3, :])
doc_coord = doc_coord.transpose()
doc_coord = doc_coord.rename(columns={0:'x', 1:'y'})
doc_coord.insert(2,'dots', [i for i in numpy.arange(1,len(text)+1)])
print(doc_coord)

          x         y  dots
0 -0.804069 -0.207993     1
1  0.126597  0.514216     2
2  0.499235 -0.716775     3
3  0.297003  0.422556     4


Расположение слов из опросника на координатной плоскости

In [62]:
%matplotlib inline

source = ColumnDataSource(data=dict(x=df.x, y=df.y, dots=df.dots))
source2 = ColumnDataSource(data=dict(x=doc_coord.x, y=doc_coord.y, dots=doc_coord.dots))

hover = HoverTool(tooltips=[
    ("x","@x"),
    ("y", "@y"),
    ("dots", "@dots")
])

TOOLS = "pan, wheel_zoom, box_zoom, reset, save, box_select, crosshair"

#output_notebook()
p = figure(plot_height=600, plot_width=800, title="Расположение слов на плоскости", tools=[hover, TOOLS])
p.circle(df.x, df.y, source=source, size=10, line_color="navy", fill_color="orange", fill_alpha=0.5)
show(p)

Расположение вопросов на координатной плоскости

In [65]:
hover2 = HoverTool(tooltips=[
    ("x","@x"),
    ("y", "@y"),
    ("вопрос ", "@dots")
])
p4 = figure(plot_height=600, plot_width=800, title="Расположение вопросов на коорд. плоскости", tools=[hover2, TOOLS])
p4.circle(doc_coord.x, doc_coord.y, source=source2, line_color="green", size=30, fill_color="green", fill_alpha=0.3)
show(p4)

Определение близости слова к ответам на вопросы

In [67]:
word= "воспитатель"
res = searchword(lsa, word)
p1 = figure(plot_height=600, plot_width=800, title="Расстояние от '"+word+"' до частей вопросов", tools="resize,save",x_axis_label='Расстояние', y_axis_label='Номер главы')
p1.segment(0, res[0], res[1], res[0], line_width=2, line_color="green", )
p1.circle(res[1], res[0], size=15, fill_color="orange", line_color="green", line_width=3, )

output_notebook()
show(p1)

᫮�� � ���᪥ ---  ��ᯨ�⥫� = � ᫮��� ---  ��ᯨ�⥫ .

���न���� ᫮�� (idx, wx, wy, word) 0	-0.30	-0.20	��ᯨ�⥫�

���㬥���, �����஢���� �� ������襬� ����ﭨ� (��������� ����ﭨ�)

1 0.505682529993 ����������
2 0.834075234278 ����������
4 0.863946615526 ����������
3 0.948540574824 ����������
������⢮ ���㬥�⮢, ᮤ�ঠ�� ������ ��� ᫮�� 4


Loading BokehJS ...

In [68]:
word= "игра"
res = searchword(lsa, word)
p1 = figure(plot_height=600, plot_width=800, title="Расстояние от '"+word+"' до частей вопросов", tools="resize,save",x_axis_label='Расстояние', y_axis_label='Номер главы')
p1.segment(0, res[0], res[1], res[0], line_width=2, line_color="green", )
p1.circle(res[1], res[0], size=15, fill_color="orange", line_color="green", line_width=3, )

output_notebook()
show(p1)

᫮�� � ���᪥ ---  ��� = � ᫮��� ---  ��� .

���न���� ᫮�� (idx, wx, wy, word) 7	-0.09	0.24	���

���㬥���, �����஢���� �� ������襬� ����ﭨ� (��������� ����ﭨ�)

2 0.345502122701 ����������
4 0.424690022919 ����������
1 0.846445662959 ����������
3 1.12567528416 ����������
������⢮ ���㬥�⮢, ᮤ�ঠ�� ������ ��� ᫮�� 4


Loading BokehJS ...

In [69]:
word= "дети"
res = searchword(lsa, word)
p1 = figure(plot_height=600, plot_width=800, title="Расстояние от '"+word+"' до частей вопросов", tools="resize,save",x_axis_label='Расстояние', y_axis_label='Номер главы')
p1.segment(0, res[0], res[1], res[0], line_width=2, line_color="green", )
p1.circle(res[1], res[0], size=15, fill_color="orange", line_color="green", line_width=3, )

output_notebook()
show(p1)

᫮�� � ���᪥ ---  ��� = � ᫮��� ---  ��� .

���न���� ᫮�� (idx, wx, wy, word) 3	0.33	0.13	���

���㬥���, �����஢���� �� ������襬� ����ﭨ� (��������� ����ﭨ�)

4 0.29151491537 ����������
2 0.433434215729 ����������
3 0.866118153454 ����������
1 1.18762823756 ����������
������⢮ ���㬥�⮢, ᮤ�ঠ�� ������ ��� ᫮�� 4


Loading BokehJS ...